[[argp_standalone]]
arch = "aarch64"
git-tree-sha1 = "f3509d1aba402f64bc02f41c9cdbed037d64d8e8"
libc = "musl"
os = "linux"

    [[argp_standalone.download]]
    sha256 = "9b415d388eda255d6e877cf5cd9c8e9b052aad213256463c53abfebb93e7c064"
    url = "https://github.com/JuliaBinaryWrappers/argp_standalone_jll.jl/releases/download/argp_standalone-v1.3.1+0/argp_standalone.v1.3.1.aarch64-linux-musl.tar.gz"
[[argp_standalone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8d1c2d103042b48fc4be34187c92980600df5c28"
libc = "musl"
os = "linux"

    [[argp_standalone.download]]
    sha256 = "46ef3d26b800ed4866b804a952ab29a90ef247845a8fb3415e01bb737a6ddb4d"
    url = "https://github.com/JuliaBinaryWrappers/argp_standalone_jll.jl/releases/download/argp_standalone-v1.3.1+0/argp_standalone.v1.3.1.armv6l-linux-musleabihf.tar.gz"
[[argp_standalone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d45166075537b4773d5ba221fac47c40e4addaad"
libc = "musl"
os = "linux"

    [[argp_standalone.download]]
    sha256 = "a5cd00df3bcd5ded54e9d896eead4e29a81ffa0cbcce3f44231fc961b7cd6742"
    url = "https://github.com/JuliaBinaryWrappers/argp_standalone_jll.jl/releases/download/argp_standalone-v1.3.1+0/argp_standalone.v1.3.1.armv7l-linux-musleabihf.tar.gz"
[[argp_standalone]]
arch = "i686"
git-tree-sha1 = "032dab3ddc7f41b3915db62931256c2553d00d03"
libc = "musl"
os = "linux"

    [[argp_standalone.download]]
    sha256 = "ad99bed436da8e015826d394e7eb430dcc0ec31b187267151d4105cefa6e1c75"
    url = "https://github.com/JuliaBinaryWrappers/argp_standalone_jll.jl/releases/download/argp_standalone-v1.3.1+0/argp_standalone.v1.3.1.i686-linux-musl.tar.gz"
[[argp_standalone]]
arch = "x86_64"
git-tree-sha1 = "ef4e7179d1aff41e15c49d6aad280f4e9eccc6b3"
libc = "musl"
os = "linux"

    [[argp_standalone.download]]
    sha256 = "1ffddf9da5c18dd0693346b281aa83f36e52a90796e92f54a8dd6795ee29f73f"
    url = "https://github.com/JuliaBinaryWrappers/argp_standalone_jll.jl/releases/download/argp_standalone-v1.3.1+0/argp_standalone.v1.3.1.x86_64-linux-musl.tar.gz"
