[[argp_standalone]]
arch = "aarch64"
git-tree-sha1 = "c8cedc9314d055f5c718d4bfc218587260edd650"
libc = "musl"
os = "linux"

    [[argp_standalone.download]]
    sha256 = "cd838dfba440c7acde7c5fd57eb281793c8232957de5c3d3f042478ab121cbbe"
    url = "https://github.com/JuliaBinaryWrappers/argp_standalone_jll.jl/releases/download/argp_standalone-v1.3.0+0/argp_standalone.v1.3.0.aarch64-linux-musl.tar.gz"
[[argp_standalone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3d12d598bc39f51530a55ad619d47977fe783b06"
libc = "musl"
os = "linux"

    [[argp_standalone.download]]
    sha256 = "95c51d52b6099e5221da03a299bd447b844f1e06c3c2f555b8ba0262c377f7ee"
    url = "https://github.com/JuliaBinaryWrappers/argp_standalone_jll.jl/releases/download/argp_standalone-v1.3.0+0/argp_standalone.v1.3.0.armv7l-linux-musleabihf.tar.gz"
[[argp_standalone]]
arch = "i686"
git-tree-sha1 = "f398411f3f13645d6fe12adaea1631d6b8d4f373"
libc = "musl"
os = "linux"

    [[argp_standalone.download]]
    sha256 = "6604f38e9be8e21319de32e00d3eabe4bad511b790bb9540615909b71924e3b9"
    url = "https://github.com/JuliaBinaryWrappers/argp_standalone_jll.jl/releases/download/argp_standalone-v1.3.0+0/argp_standalone.v1.3.0.i686-linux-musl.tar.gz"
[[argp_standalone]]
arch = "x86_64"
git-tree-sha1 = "089bf78fdf75c575d5e2ac91a1f087760f93f95b"
libc = "musl"
os = "linux"

    [[argp_standalone.download]]
    sha256 = "74c954db8e5c508cf16eedc26c549790392e45d07a8bfe600f9f085b943a7e19"
    url = "https://github.com/JuliaBinaryWrappers/argp_standalone_jll.jl/releases/download/argp_standalone-v1.3.0+0/argp_standalone.v1.3.0.x86_64-linux-musl.tar.gz"
